server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**
        - id: pagamento_route
          uri: http://localhost:8082
          predicates:
            - Path=/pagamento/**
        - id: crud_route
          uri: http://localhost:8081
          predicates:
            - Path=/crud/**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka